### ISSUE TITLE
Java version is determined by the ArkCase version, which conflicts with ongoing versioning structures

### ISSUE THREAD

**Issue by fergusonna** [ArkCase/arkcase-ce#652]
In the following ansible task, the version number of ArkCase is used to define the Java version. 

```
- name: set Java 8 as Java Home (versions below 2023.02)
  set_fact:
    java_home_version: "/usr/lib/jvm/java-1.8.0-openjdk"
  when: arkcase_version != "" and arkcase_version is version('2023.02', '<')

- name: set Java 11 as Java Home (versions equal and above 2023.02)
  set_fact:
    java_home_version: "/usr/lib/jvm/java-11-openjdk"
  when: arkcase_version == "" or arkcase_version is version('2023.02', '>=')
``` 

Instead of using the arkcase_version (as some customers have their own fork of ArkCase with different versioning schemes), we should have a dedicated java version property. 

This would prevent unexpected configuration and be much more clear.
